#! /bin/sh


echo
echo ' Testing parallel SelfSimTrafficForJitterMeasure project'
echo

rm -rf comm
mkdir comm
mkdir comm/read

# make sure HOSTNAME is exported as some distors no longer export it by default
if test "$HOSTNAME" = ""; then
  export HOSTNAME='hostname'
fi

export NEDPATH=..
../SelfSimTrafficForJitterMeasure -p0,3 $* > SelfSimTrafficForJitterMeasure-0.log &
../SelfSimTrafficForJitterMeasure -p1,3 $* > SelfSimTrafficForJitterMeasure-1.log &
../SelfSimTrafficForJitterMeasure -p2,3 $* > SelfSimTrafficForJitterMeasure-2.log &
